server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/agendeme_notificacoes_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: ms-notificacoes
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.value.default.type: br.com.acompanheme.notificacoes.dto.SolicitacaoNotificacaoDTO
  mail:
    host: localhost
    port: 1025
    username: nao-responda@acompanhe-me.local
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
