package br.com.acompanheme.gestaosolicitacoes.model.enums;

/**
 * TipoEvento
 */
public enum TipoEvento {

    SOLICITACAO_REGISTRADA,
    SOLICITACAO_EM_ANALISE,
    SOLICITACAO_EM_FILA,
    SOLICITACAO_DEVOLVIDA,
    SOLICITACAO_PRIORIDADE_ALTERADA,
    SOLICITACAO_LOCAL_DEFINIDO,
    SOLICITACAO_CONFIRMADA,
    SOLICITACAO_REJEITADA,
    SOLICITACAO_CANCELADA,
    SOLICITACAO_CONCLUIDA
}
