package br.com.acompanheme.gestaosolicitacoes.model.enums;

/**
 * TipoEvento
 */
public enum TipoEvento {

    SOLICITACAO_REGISTRADA,
    SOLICITACAO_EM_ANALISE,
    SOLICITACAO_DEVOLVIDA,
    SOLICITACAO_NEGADA,
    SOLICITACAO_APROVADA,
    SOLICITACAO_PRIORIDADE_ALTERADA,
    SOLICITACAO_LOCAL_DEFINIDO,
    SOLICITACAO_OFERTA_ACEITA,
    SOLICITACAO_OFERTA_RECUSADA,
    SOLICITACAO_CANCELADA,
    SOLICITACAO_CONCLUIDA
}
